export const iconifyIconList: string[] = [
  'mdi:list-box-outline',
  'mdi:account-multiple-check-outline',
  'mdi:alpha-f-box-outline',
  'mdi:arm-flex-outline',
  'mdi:account-group-outline',
  'mdi:account-cog-outline',
  'mdi:account-heart-outline',
  'mdi:database-cog-outline',
  'mdi:cloud-check-variant-outline',
  'mdi:record-circle-outline',
  'mdi:timer-cog-outline',
  'mdi:calendar-clock-outline',
  'mdi:invoice-text-arrow-left-outline',
  'mdi:invoice-text-clock-outline',
  'mdi:account-file-text-outline',
  'mdi:email-fast-outline',
  'mdi:server-outline',
  'mdi:toolbox-outline',
  'mdi:email-arrow-right-outline',
  'mdi:folder-cog-outline',
  'mdi:book-heart-outline',
  'mdi:book-open-page-variant-outline',
  'mdi:book-open-variant-outline',
  'mdi:format-list-numbered',
  'ic:outline-reduce-capacity',
  'ic:outline-other-houses',
  'ic:outline-cached',
  'ic:outline-notifications',
  'fa-brands:alipay'
];

export const localIconList: string[] = ['custom-icon', 'activity', 'at-sign', 'cast', 'chrome', 'copy', 'wind'];
